// Auto-generated by scripts/generate-migrations.ts — do not edit manually.
import journal from './meta/_journal.json';
import m0000 from './0000_harsh_meggan.sql';
import m0001 from './0001_glorious_boomer.sql';
import m0002 from './0002_steady_namora.sql';
import m0003 from './0003_absent_aaron_stack.sql';
import m0004 from './0004_smiling_norman_osborn.sql';
import m0005 from './0005_romantic_nehzno.sql';
import m0006 from './0006_lean_storm.sql';
import m0007 from './0007_exercise_types_muscle_groups.sql';
import m0008 from './0008_advanced_schedules.sql';
import m0009 from './0009_nullable_performed_at.sql';
import m0010 from './0010_import_batches.sql';
import m0011 from './0011_import_edited_at.sql';
import m0012 from './0012_collapse_schedule_kind.sql';
import m0013 from './0013_sets_fields_set_types.sql';
import m0014 from './0014_settype_fields.sql';
import m0015 from './0015_template_exercise_color.sql';
import m0016 from './0016_progression_mode.sql';
import m0017 from './0017_set_type_progression_goal.sql';
import m0018 from './0018_template_set_progression_goal.sql';
import m0019 from './0019_drop_progression_mode.sql';
import m0020 from './0020_performed_set_field_definitions.sql';

export default {
  journal,
  migrations: {
    m0000,
    m0001,
    m0002,
    m0003,
    m0004,
    m0005,
    m0006,
    m0007,
    m0008,
    m0009,
    m0010,
    m0011,
    m0012,
    m0013,
    m0014,
    m0015,
    m0016,
    m0017,
    m0018,
    m0019,
    m0020,
  },
};
