// Auto-generated by scripts/generate-migrations.ts — do not edit manually.
import journal from './meta/_journal.json';
import m0000 from './0000_harsh_meggan.sql';

export default {
  journal,
  migrations: {
    m0000,
  },
};
