// Auto-generated by scripts/generate-migrations.ts — do not edit manually.
import journal from './meta/_journal.json';
import m0000 from './0000_harsh_meggan.sql';
import m0001 from './0001_glorious_boomer.sql';
import m0002 from './0002_steady_namora.sql';
import m0003 from './0003_absent_aaron_stack.sql';
import m0004 from './0004_smiling_norman_osborn.sql';
import m0005 from './0005_romantic_nehzno.sql';
import m0006 from './0006_lean_storm.sql';
import m0007 from './0007_exercise_types_muscle_groups.sql';
import m0008 from './0008_advanced_schedules.sql';
import m0009 from './0009_nullable_performed_at.sql';
import m0010 from './0010_import_batches.sql';
import m0011 from './0011_import_edited_at.sql';

export default {
  journal,
  migrations: {
    m0000,
    m0001,
    m0002,
    m0003,
    m0004,
    m0005,
    m0006,
    m0007,
    m0008,
    m0009,
    m0010,
    m0011,
  },
};
