/**
 * Reads the Drizzle migration journal and generates the migrations index file
 * so you never have to maintain it by hand.
 *
 * Run: bun run db:generate (called automatically after drizzle-kit generate)
 */

import { existsSync, readFileSync, rmSync, writeFileSync } from 'fs';
import { join } from 'path';

const drizzleDir = join(import.meta.dir, '../src/data/local/drizzle');
const journalPath = join(drizzleDir, 'meta/_journal.json');
const outPath = join(drizzleDir, 'index.ts');
const generatedExpoBundlePath = join(drizzleDir, 'migrations.js');

const journal = JSON.parse(readFileSync(journalPath, 'utf-8'));
const entries: { tag: string }[] = journal.entries;

const imports = entries
  .map((e, i) => `import m${String(i).padStart(4, '0')} from './${e.tag}.sql';`)
  .join('\n');

const migrationEntries = entries
  .map((_, i) => `    m${String(i).padStart(4, '0')}`)
  .join(',\n');

const source = `// Auto-generated by scripts/generate-migrations.ts — do not edit manually.
import journal from './meta/_journal.json';
${imports}

export default {
  journal,
  migrations: {
${migrationEntries},
  },
};
`;

writeFileSync(outPath, source);
if (existsSync(generatedExpoBundlePath)) {
  rmSync(generatedExpoBundlePath);
}
console.log(`Generated migrations index with ${entries.length} migration(s).`);
