spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT:3306}/${DB_NAME:dumbbell}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
