events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/conf.d/upstream.conf;

    # Production
    server {
        listen 80;

        location / {
            proxy_pass         http://dumbbell_backend;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }
    }

    # Staging
    server {
        listen 8081;

        location / {
            proxy_pass         http://dumbbell-backend-staging:8080;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
        }
    }
}
